pipeline:
  docker:
    image: plugins/docker
    username: bjackson1test
    password: Dr0neSp1ke123
    repo: bjackson1test/sc
    tag: latest
  build:
    image: bjackson1test/sc:latest
    commands:
      - curl -v http://localhost

